const $=id=>document.getElementById(id);let state={topology:{nodes:[],links:[]},audit:[],config:{},invites:[],manualLinks:[]},timer;
const titles={overview:['Network overview','Health and connectivity at a glance'],peers:['Peers','Inventory, roles and endpoints'],topology:['Topology','Live telemetry and routing graph'],access:['Setup keys','Enroll new devices securely'],events:['Events','Administrative audit trail'],settings:['Settings','Topology policy and device administration']};
function toast(text){let x=$('toast');x.textContent=text;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
async function api(path,options={}){options.headers={...(options.headers||{}),'X-Mesh-Token':$('token').value};let r=await fetch(path,options),body=await r.json();if(!r.ok)throw Error(body.error||r.statusText);return body}
function page(name){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$('pageTitle').textContent=titles[name][0];$('subtitle').textContent=titles[name][1]}
document.querySelectorAll('nav button').forEach(x=>x.onclick=()=>page(x.dataset.page));
function graph(svg,t){let n=t.nodes||[],e=t.links||[],p={},cx=500,cy=270,R=Math.min(205,80+n.length*12);n.forEach((x,i)=>{let a=i*Math.PI*2/Math.max(1,n.length)-Math.PI/2;p[x.node_id]={x:cx+R*Math.cos(a),y:cy+R*Math.sin(a)}});svg.innerHTML=e.map(x=>{let a=p[x.a],b=p[x.b];if(!a||!b)return'';let label=x.rtt_ms?Math.round(x.rtt_ms)+' ms':'no RTT';return `<line class="edge ${x.status||'unknown'}" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/><text class="svgLabel" x="${(a.x+b.x)/2}" y="${(a.y+b.y)/2}">${label}</text>`}).join('')+n.map(x=>{let q=p[x.node_id],ring=x.nat_type==='symmetric'?`<circle class="sym" cx="${q.x}" cy="${q.y}" r="25"/>`:'';return `<g data-peer="${x.node_id}">${ring}<circle class="node ${x.role}" cx="${q.x}" cy="${q.y}" r="19"/><text class="svgLabel" text-anchor="middle" x="${q.x}" y="${q.y+40}">${x.node_id.slice(0,8)}</text></g>`}).join('');svg.querySelectorAll('[data-peer]').forEach(x=>x.onclick=()=>showPeer(x.dataset.peer))}
function showPeer(id){let x=state.topology.nodes.find(n=>n.node_id===id);if(!x)return;page('topology');$('rolePeer').value=id;$('roleValue').value=x.requested_role||'auto';$('nodeDetail').innerHTML=`<b>${x.node_id}</b><br>Role ${x.role} · requested ${x.requested_role||'auto'} · NAT ${x.nat_type} · ${x.mesh_ip} · ${x.endpoint} · capacity ${x.capacity}`}
function render(){let t=state.topology,n=t.nodes||[],links=t.links||[],rtts=links.filter(x=>x.rtt_ms).map(x=>x.rtt_ms),up=links.filter(x=>x.status==='up').length;$('nodesN').textContent=n.length;$('superN').textContent=n.filter(x=>x.role==='superpeer').length;$('upN').textContent=up;$('rttN').textContent=rtts.length?Math.round(rtts.reduce((a,b)=>a+b,0)/rtts.length)+' ms':'—';$('healthPct').textContent=(links.length?Math.round(up*100/links.length):0)+'% available';$('peerBadge').textContent=n.length;graph($('overviewGraph'),t);graph($('topologyGraph'),t);$('healthList').innerHTML=links.slice(0,8).map(x=>`<p><span class="statusDot" style="background:${x.status==='up'?'#22c55e':'#ef4444'}"></span> ${x.a.slice(0,6)} → ${x.b.slice(0,6)} <b>${x.rtt_ms?Math.round(x.rtt_ms)+'ms':x.status}</b></p>`).join('')||'<p class="muted">No links yet</p>';$('eventPreview').innerHTML=state.audit.slice(0,5).map(x=>`<p><b>${x.event}</b><br><span class="muted">${new Date(x.created_at*1000).toLocaleString()}</span></p>`).join('');renderPeers();$('auditRows').innerHTML=state.audit.map(x=>`<tr><td>${new Date(x.created_at*1000).toLocaleString()}</td><td>${x.event}</td><td>${x.detail}</td></tr>`).join('');$('inviteRows').innerHTML=state.invites.map(x=>`<tr><td><code>${x.token}</code></td><td>${new Date(x.expires_at*1000).toLocaleTimeString()}</td><td><span class="chip">${x.used?'used':'active'}</span></td></tr>`).join('');for(let k in state.config){let f=$('settingsForm').elements[k];if(f)f.value=state.config[k]}$('removePeer').innerHTML=n.map(x=>`<option value="${x.node_id}">${x.node_id.slice(0,12)} · ${x.mesh_ip}</option>`).join('')}
function renderPeers(){let q=$('peerSearch').value.toLowerCase(),role=$('roleFilter').value,nat=$('natFilter').value;let n=(state.topology.nodes||[]).filter(x=>(!role||x.role===role)&&(!nat||x.nat_type===nat)&&(!q||JSON.stringify(x).toLowerCase().includes(q)));$('peerRows').innerHTML=n.map(x=>`<tr><td><span class="statusDot"></span> online</td><td><b>${x.node_id.slice(0,12)}</b></td><td><span class="chip">${x.role}</span></td><td>${x.nat_type}</td><td>${x.mesh_ip}</td><td>${x.endpoint}</td><td>${x.capacity}</td><td><button class="ghost" onclick="showPeer('${x.node_id}')">Inspect</button></td></tr>`).join('')}
function renderEditor(){let n=state.topology.nodes||[],options=n.map(x=>`<option value="${x.node_id}">${x.node_id.slice(0,10)} · ${x.mesh_ip} · ${x.role}</option>`).join('');for(let id of ['edgeA','edgeB','rolePeer'])$(id).innerHTML=options;let telemetry=new Map((state.topology.links||[]).map(x=>[edgeKey(x.a,x.b),x]));$('edgeRows').innerHTML=(state.manualLinks||[]).map((x,i)=>{let live=telemetry.get(edgeKey(x.a,x.b));return `<tr><td>${x.a.slice(0,10)}</td><td>${x.b.slice(0,10)}</td><td>${x.cost}</td><td>${live?.rtt_ms?Math.round(live.rtt_ms)+' ms':'—'}</td><td><button class="ghost" onclick="deleteEdge(${i})">Remove</button></td></tr>`}).join('')||'<tr><td colspan="5" class="muted">Automatic topology is active. Add a link to create a manual override.</td></tr>'}
const edgeKey=(a,b)=>a<b?a+'|'+b:b+'|'+a;async function publishEdges(){await api('/v1/admin/graph',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({links:state.manualLinks})});toast(state.manualLinks.length?'Manual topology published':'Automatic topology restored');await load()}async function deleteEdge(i){state.manualLinks.splice(i,1);await publishEdges()}
const baseRender=render;render=()=>{state.invites=state.invites||[];state.audit=state.audit||[];baseRender();if(!state.invites.length)$('inviteRows').innerHTML='<tr><td colspan="3" class="muted">No active setup keys. Generate one to enroll a device.</td></tr>';if(!state.audit.length)$('auditRows').innerHTML='<tr><td colspan="3" class="muted">No events recorded yet.</td></tr>';renderEditor()};
async function load(){try{let [config,topology,audit,invites,graphData]=await Promise.all([api('/v1/admin/config'),api('/v1/admin/topology'),api('/v1/admin/audit'),api('/v1/admin/invites'),api('/v1/admin/graph')]);state={config,topology,audit,invites,manualLinks:graphData.links||[]};$('liveDot').classList.add('live');$('liveText').textContent='Live · '+new Date().toLocaleTimeString();render()}catch(e){$('liveDot').classList.remove('live');$('liveText').textContent='Disconnected';toast(e.message)}}
$('connect').onclick=()=>{sessionStorage.setItem('meshToken',$('token').value);load();clearInterval(timer);timer=setInterval(load,10000)};$('refresh').onclick=load;$('peerSearch').oninput=renderPeers;$('roleFilter').onchange=renderPeers;$('natFilter').onchange=renderPeers;$('fitGraph').onclick=()=>graph($('topologyGraph'),state.topology);
$('settingsForm').onsubmit=async e=>{e.preventDefault();let body={};for(let x of new FormData(e.target))body[x[0]]=Number(x[1]);await api('/v1/admin/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast('Policy saved and pushed');load()};
$('addEdge').onclick=async()=>{let a=$('edgeA').value,b=$('edgeB').value,cost=Number($('edgeCost').value);if(!a||!b||a===b)return toast('Choose two different peers');let key=edgeKey(a,b),existing=state.manualLinks.find(x=>edgeKey(x.a,x.b)===key);if(existing)existing.cost=cost;else state.manualLinks.push({a,b,cost});await publishEdges()};$('autoGraph').onclick=async()=>{if(confirm('Discard manual links and restore automatic topology?')){state.manualLinks=[];await publishEdges()}};$('saveRole').onclick=async()=>{let id=$('rolePeer').value,role=$('roleValue').value;if(!id)return;await api('/v1/admin/nodes/'+encodeURIComponent(id)+'/role',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({role})});toast('Role policy applied');load()};
$('createInvite').onclick=async()=>{let x=await api('/v1/admin/invites',{method:'POST'});$('newInvite').textContent=x.invite_token;toast('Setup key created');load()};$('loadGraph').onclick=async()=>{let x=await api('/v1/admin/graph');$('graphText').value=(x.links||[]).map(e=>`${e.a} ${e.b} ${e.cost}`).join('\n')};$('saveGraph').onclick=async()=>{let text=$('graphText').value.trim(),links=text?text.split(/\n+/).map(x=>{let p=x.trim().split(/\s+/);return{a:p[0],b:p[1],cost:Number(p[2])}}):[];await api('/v1/admin/graph',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({links})});toast('Graph published');load()};$('removeButton').onclick=async()=>{let id=$('removePeer').value;if(id&&confirm('Remove this peer?')){await api('/v1/admin/nodes/'+encodeURIComponent(id),{method:'DELETE'});toast('Peer removed');load()}};
$('token').value=sessionStorage.getItem('meshToken')||'';if($('token').value)$('connect').click();
